# Generated by Django 5.1.3 on 2024-12-23 20:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'unique': 'Produto com este nome já existe.'}, help_text='Nome do produto', max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, help_text='Slug do produto - gerado automaticamente.', max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto.', max_length=10000)),
                ('imagem', models.ImageField(blank=True, help_text='Imagem do produto.', null=True, upload_to='produtos/')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do produto em reais - mínimo R$ 0,01.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Produto ativo.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização.')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Vendedor ativo.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização.')),
                ('person', models.OneToOneField(help_text='Pessoa associada ao vendedor.', on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
                ('produtos', models.ManyToManyField(blank=True, help_text='Produtos disponíveis para venda.', related_name='vendedores', to='vender.produto')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
            },
        ),
    ]
