# Generated by Django 5.1.3 on 2024-12-10 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendedores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_vendedor", models.CharField(max_length=200)),
                ("Produto", models.CharField(max_length=50)),
                ("imagem_produto", models.ImageField(upload_to="media/vendedores")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
            ],
        ),
    ]
