# Generated by Django 5.1.3 on 2024-12-10 22:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0002_produto_vendedor_delete_vendedores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do produto.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do produto.', null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Produto ativo.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='Slug do produto - gerado automaticamente.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do produto em reais - mínimo R$ 0,01.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação.'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Vendedor ativo.'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='person',
            field=models.OneToOneField(help_text='Pessoa associada ao vendedor.', on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='produtos',
            field=models.ManyToManyField(blank=True, help_text='Produtos disponíveis para venda.', related_name='vendedores', to='vender.produto'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização.'),
        ),
    ]
