# Generated by Django 5.1.3 on 2024-12-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0003_alter_produto_created_at_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do produto.', max_length=10000),
        ),
    ]
